<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="bmlUsuarios.aspx.cs" Inherits="Vistas.bmlUsuarios" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

            <div>
            <asp:Label ID="Label2" CssClass="text-center"  Style="display: block" runat="server" Font-Size="XX-Large" Text="ALTA BAJA Y MODIFICACION DE USUARIOS"></asp:Label>
            <br />
            <asp:Label ID="lbl_res" CssClass="text-center text-success" Style="display: block" runat="server" Font-Size="X-Large"></asp:Label>
            <br />            

            <div class="menu-btn">
                <asp:Button ID="btn_add" CssClass="btn btn-primary" runat="server" OnClick="btn_add_Click" Text="Añadir Usuario" />
            <asp:Button ID="btn_mod" CssClass="btn btn-primary" runat="server" OnClick="btn_mod_Click" Text="Ver/Editar/Eliminar Usuario" />
            
            </div>
                <br />
&nbsp;&nbsp;&nbsp;
            <asp:Panel ID="Panel1" runat="server" class="container" Visible="False">
                <asp:Label ID="Label3" class="titulo" runat="server" Text="Añadir usuario"></asp:Label>
                <br />
                <br />
                <asp:Label ID="Label4" runat="server" Text="Usuario: "></asp:Label>
                <asp:TextBox ID="txtUsuario" CssClass="form-control" runat="server" ></asp:TextBox>

                <asp:Label ID="Label6" runat="server" Text="Nombre"></asp:Label>&nbsp;&nbsp;
                <asp:TextBox ID="txtNombre" CssClass="form-control" runat="server" MaxLength="250" ></asp:TextBox> 

                <asp:RegularExpressionValidator ID="RegularExpressionValidator2" runat="server" ControlToValidate="txtNombre" Font-Bold="True" Font-Overline="False" ForeColor="#CC0000" ValidationExpression="^[a-zA-Z ]*$">El nombre no puede tener numeros ni simbolos</asp:RegularExpressionValidator>
                <br />

                <asp:Label ID="Label5" runat="server" Text="Apellido"></asp:Label> &nbsp;&nbsp;
                <asp:TextBox ID="txtApellido" CssClass="form-control" runat="server" MaxLength="250" ></asp:TextBox>

                <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" ControlToValidate="txtApellido" Font-Bold="True" Font-Overline="False" ForeColor="#CC0000" ValidationExpression="^[a-zA-Z ]*$">El Apellido no puede tener numeros ni simbolos</asp:RegularExpressionValidator>
                <br />

                <asp:Label ID="Label7" runat="server" Text="Mail"></asp:Label> &nbsp;&nbsp;
                <asp:TextBox ID="txtMail" TextMode="Email" CssClass="form-control" runat="server" MaxLength="250" ></asp:TextBox>

                <asp:Label ID="Label8" runat="server" Text="Contraseña"></asp:Label> &nbsp;&nbsp;
                <asp:TextBox ID="txtContra" runat="server" CssClass="form-control" MaxLength="250" TextMode="Password" ></asp:TextBox>

                &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;
                <br />

                <asp:Button ID="btnAgregarUsuario" CssClass="btn btn-success" runat="server" OnClick="btnAgregarUsuario_Click" Text="Añadir usuario" />
                <br />
            </asp:Panel>

            <asp:Panel ID="Panel2"  runat="server" Visible="False">
                            <h4 class="titulo text-center">Ver/Editar/Eliminar Usuarios</h4>
                <asp:GridView ID="grdUsuario" CssClass="table table-hover" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="grdUsuario_RowDeleting" OnRowUpdating="grdUsuario_RowUpdating" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3"  GridLines="Vertical" AutoGenerateColumns="False" OnRowCancelingEdit="grdUsuario_RowCancelingEdit" OnRowEditing="grdUsuario_RowEditing">
                    <AlternatingRowStyle BackColor="#CCCCCC" />
                    <Columns>
                        <asp:TemplateField HeaderText="Usuario">
                            <ItemTemplate>
                                <asp:Label ID="lblUsu" runat="server" Text='<%# Bind("user_usuarios") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Apellido">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtApellidoEdit" runat="server" Text='<%# Bind("apellido_usuarios") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblApellido" runat="server" Text='<%# Bind("apellido_usuarios") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Nombre">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtNombreEdit" runat="server" Text='<%# Bind("nombre_usuarios") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblNombre" runat="server" Text='<%# Bind("nombre_usuarios") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Mail">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtMailEdit" runat="server" Text='<%# Bind("mail_usuarios") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblMail" runat="server" Text='<%# Bind("mail_usuarios") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Contraseña">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtContraEdit" runat="server" Text='<%# Bind("password_usuarios") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblContra" runat="server" Text='<%# Bind("password_usuarios") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>

                    </Columns>
                    <EmptyDataTemplate>
                        <asp:Label ID="Label1" runat="server" Text="No se han encontrado resultados"></asp:Label>
                    </EmptyDataTemplate>
                    <FooterStyle BackColor="#CCCCCC" />
                    <HeaderStyle BackColor="Gray" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                    <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F1F1F1" />
                    <SortedAscendingHeaderStyle BackColor="#808080" />
                    <SortedDescendingCellStyle BackColor="#CAC9C9" />
                    <SortedDescendingHeaderStyle BackColor="#383838" />
                </asp:GridView>
            </asp:Panel>
            <br />
&nbsp;&nbsp;&nbsp;
            <br />

        </div>





    
    <!-------------DATATABLES--------------->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/jq-3.6.0/dt-1.13.1/datatables.min.js"></script>

    <!--    <script type="text/javascript">
        $(document).ready(function () {
            <%-- $('#<%=grdAlumnos%>').prepend($("<thead></thead>").append($(this).find("tr:first"))).DataTable(); --%>
            $(".table").prepend($("<thead></thead>").append($(this).find("tr:first"))).DataTable();
        });
    </script>-->

    <%if (grdUsuario.Rows.Count > 0) { %>
    <script type="text/javascript">
        $(document).ready(function () {
            // Setup - add a text input to each footer cell
            $('.table thead tr')
                .clone(true)
                .addClass('filters')
                .appendTo('.table thead');

            var table = $('.table').DataTable({
                orderCellsTop: true,
                fixedHeader: true,
                initComplete: function () {
                    var api = this.api();

                    // For each column
                    api
                        .columns()
                        .eq(0)
                        .each(function (colIdx) {
                            // Set the header cell to contain the input element
                            var cell = $('.filters th').eq(
                                $(api.column(colIdx).header()).index()
                            );
                            var title = $(cell).text();
                            $(cell).html('<input type="text" placeholder="' + title + '" />');

                            // On every keypress in this input
                            $(
                                'input',
                                $('.filters th').eq($(api.column(colIdx).header()).index())
                            )
                                .off('keyup change')
                                .on('change', function (e) {
                                    // Get the search value
                                    $(this).attr('title', $(this).val());
                                    var regexr = '({search})'; //$(this).parents('th').find('select').val();

                                    var cursorPosition = this.selectionStart;
                                    // Search the column for that value
                                    api
                                        .column(colIdx)
                                        .search(
                                            this.value != ''
                                                ? regexr.replace('{search}', '(((' + this.value + ')))')
                                                : '',
                                            this.value != '',
                                            this.value == ''
                                        )
                                        .draw();
                                })
                                .on('keyup', function (e) {
                                    e.stopPropagation();

                                    $(this).trigger('change');
                                    $(this)
                                        .focus()[0]
                                        .setSelectionRange(cursorPosition, cursorPosition);
                                });
                        });
                },
            });
        });
    </script>
    <%} %>



</asp:Content>




